use LocacaoSalas

INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(45,'Rua 15','Limão',220,'Sla 515','Luxuria','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(34,'Rua do Terror','Passa fundo',100,'5º andar','Ipanema','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(12,'Av 21','Viradouro',45,'Terreo','Rio das Ostras','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(42,'Av 21','Viradouro',45,'1º andar','Rio das Ostras','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(9,'Rua 15','Limão',220,'Sla 517','Luxuria','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(10,'Av 21','Viradouro',45,'15º andar','Rio das Ostras','RJ')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(99,'Viela Sábia','Vianinha',55,'Sla 202','Nova Lima','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(67,'Rua Papel','Ermelinda',67,'9º andar','Nova Lima','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(88,'Rua João Carlos','Horto',1130,'Pilotis','Belo Horizonte','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(89,'Rua João Carlos','Horto',1130,'Terreo','Belo Horizonte','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(44,'Viela Sábia','Vianinha',55,'Sla 304','Nova Lima','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(11,'Rua João Carlos','Horto',1130,'10º andar','Belo Horizonte','MG')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(1,'Rua Figueiredo','Paqueta',1000,'Sla 101','São Paulo','SP')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(2,'Rua Neves','Palmeiras',22,'9º andar','Lagoinha','SP')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(6,'Rua Ribeiro de Abreu','Cruzeiro',5001,'Terreo','Serra','SP')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(90,'Rua Ribeiro de Abreu','Cruzeiro',5001,'6º andar','Serra','SP')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(78,'Rua Figueiredo','Paqueta',1000,'Sla 908','São Paulo','SP')
INSERT INTO Enderecos(codend,logradouro,bairro,numero,complemento,cidade,estado)VALUES(77,'Rua Ribeiro de Abreu','Cruzeiro',5001,'8º andar','Serra','SP')
